id: ID01C57E9
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-21T21:05:17+00:00'
last_modified: '2022-06-08T08:34:57.649387+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W2CZ7872
  title: ངག་དབང་བསྟན་འཛིན་ནོར་བུའི་རྣམ་ཐར་འཆི་མེད་བདུད་རྩིའི་རོལ་མཚོ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    1EF8:
      image_group_id: I1KG12117
      title: ''
      total_pages: 990
      order: 1
      base_file: 1EF8.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
