id: P009095
initial_creation_type: ocr
created_at: 21/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W2CZ7872
  title: ངག་དབང་བསྟན་འཛིན་ནོར་བུའི་རྣམ་ཐར་འཆི་མེད་བདུད་རྩིའི་རོལ་མཚོ།
  author: ''
  volumes:
    9ce1afc88b9f41cb9d367b35da5cfcdd:
      image_group_id: I1KG12117
      title: ''
      volume_number: 1
      total_pages: 990
      base_file: v001.txt
